title: Your awesome title
description: >- # this means to ignore newlines until "email:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

email: your-email@example.com
author: Your name

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social Media Links
# Uncomment and add your usernames to display social media links in the footer
github_username:  jekyll
twitter_username: jekyllrb
# instagram_username: 
# linkedin_username: 

# Show excerpt (preview) of posts on homepage
# Set to true to display a short preview of each post
show_excerpts: true
excerpt_separator: <!-- break -->

# Pages to display in header navigation
# Uncomment and add page paths in desired order
# header_pages:
#   - about.html

# Pagination settings
paginate: 10              # Number of posts per page
paginate_path: "/page/:num/"  # URL path for pagination pages

# Permalink format for post URLs
# /:title/ will generate URLs like: example.com/post-title/
permalink: /:title/